import { Listing } from './types';

export const initialListings: Listing[] = [
  {
    id: 1,
    district: 'Birbhum',
    po: 'Bolpur',
    road: 'NH14',
    landmark: 'Near Visva-Bharati University',
    price: '8,00,000',
    priceNum: 800000,
    negotiable: true,
    mobile: '9876500000',
    hasVideo: false,
    photos: [],
    size: '10',
    unit: 'কাঠা',
    type: 'বাসস্থান',
    facing: 'উত্তর',
    maps: 'https://maps.google.com/?q=Bolpur+West+Bengal',
    verified: true,
    sold: false,
    soldAt: null
  },
  {
    id: 2,
    district: 'Birbhum',
    po: 'Suri',
    road: 'Village Road',
    landmark: 'Near Old Pond',
    price: '3,50,000',
    priceNum: 350000,
    negotiable: false,
    mobile: '7012400000',
    hasVideo: false,
    photos: [],
    size: '5',
    unit: 'কাঠা',
    type: 'কৃষি জমি',
    facing: 'দক্ষিণ',
    maps: '',
    verified: true,
    sold: false,
    soldAt: null
  },
  {
    id: 3,
    district: 'Murshidabad',
    po: 'Berhampore',
    road: 'NH12',
    landmark: 'Near Collectorate',
    price: '12,00,000',
    priceNum: 1200000,
    negotiable: true,
    mobile: '9123400000',
    hasVideo: false,
    photos: [],
    size: '2',
    unit: 'বিঘা',
    type: 'বাণিজ্যিক',
    facing: 'পূর্ব',
    maps: 'https://maps.google.com/?q=Berhampore+West+Bengal',
    verified: true,
    sold: false,
    soldAt: null
  },
  {
    id: 4,
    district: 'Bankura',
    po: 'Bishnupur',
    road: 'State Highway 5',
    landmark: 'Near Temple',
    price: '4,50,000',
    priceNum: 450000,
    negotiable: true,
    mobile: '8765400000',
    hasVideo: false,
    photos: [],
    size: '8',
    unit: 'কাঠা',
    type: 'কৃষি জমি',
    facing: 'উত্তর',
    maps: '',
    verified: true,
    sold: false,
    soldAt: null
  }
];
